sudo: required
services:
  - docker

before_install: 
  - docker build -t krenarradoniqi/docker-react -f Dockerfile.dev .

script: 
  - docker run krenarradoniqi/docker-react npm run test -- --coverage